### ISSUE TITLE
UnicodeDecodeError during install process on Windows 10

### ISSUE THREAD

**Issue by xenogew** [dbcli/mssql-cli#180]
While I tried to install client via command `pip install mssql-cli`.
It throw this error and cannot finish the installing process.

```
Exception:
Traceback (most recent call last):
  File "c:\ext\python\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 45: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ext\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\ext\python\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\ext\python\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\ext\python\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\ext\python\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\ext\python\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 45: invalid start byte
```

And I never touch Python before, so I don't have any idea about these errors.
Can anyone help me to fix the issue.

**Python runtime:** 3.6.4
**OS:** Windows 10 Pro 64bit
**Python installed path:** C:\ext\Python

**Comment by pensivebrian** [comment]
That error is in pip, so it seems pip isn't dealing with a console set to utf-8 as the encoding very well. 

Can you try opening a brand new console, and running the pip upgrade? If it fails, can you report encoding from your console using the following command:
`> chcp`

Then, can try changing your codepage to 437 using the following command, and re-run the pip upgrade?
`> chcp 437`

**Comment by xenogew** [comment]
To @pensivebrian 
What I've done is run the command you recommended `chcp 473` (former value is **932**)
and then run upgrade pip command and it said, already up-to-date as a result.

But it's quite look like still throw the same error.
Here is the whole output of `pip install mssql-cli` I called.
```
Collecting mssql-cli
  Using cached mssql_cli-0.10.0-py2.py3-none-win32.whl
Collecting humanize>=0.5.1 (from mssql-cli)
  Using cached humanize-0.5.1.tar.gz
Requirement already satisfied: click>=4.1 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: wheel>=0.29.0 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: applicationinsights>=0.11.1 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: cli-helpers<1.0.0,>=0.2.3 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: sqlparse<0.3.0,>=0.2.2 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: enum34>=1.1.6 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: prompt-toolkit<1.1.0,>=1.0.10 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: configobj>=5.0.6 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: future>=0.16.0 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: Pygments>=2.0 in c:\ext\python\lib\site-packages (from mssql-cli)
Requirement already satisfied: backports.csv>=1.0.0 in c:\ext\python\lib\site-packages (from cli-helpers<1.0.0,>=0.2.3->mssql-cli)
Requirement already satisfied: terminaltables>=3.0.0 in c:\ext\python\lib\site-packages (from cli-helpers<1.0.0,>=0.2.3->mssql-cli)
Requirement already satisfied: wcwidth in c:\ext\python\lib\site-packages (from prompt-toolkit<1.1.0,>=1.0.10->mssql-cli)
Requirement already satisfied: six>=1.9.0 in c:\ext\python\lib\site-packages (from prompt-toolkit<1.1.0,>=1.0.10->mssql-cli)
Building wheels for collected packages: humanize
  Running setup.py bdist_wheel for humanize ... error
  Failed building wheel for humanize
  Running setup.py clean for humanize
Failed to build humanize
Installing collected packages: humanize, mssql-cli
  Running setup.py install for humanize ... error
Exception:
Traceback (most recent call last):
  File "c:\ext\python\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 45: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ext\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\ext\python\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\ext\python\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\ext\python\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\ext\python\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\ext\python\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 45: invalid start byte
```

Sorry for information what I have just only this and don't have any idea about Python.
Wish you still help me solve this problem.

**Comment by pensivebrian** [comment]
So this looks like an known issue in pip 9 - see the thread in issue https://github.com/pypa/pip/issues/4110. In particular, cp932 is one of the problematic code pages.

I see two possible workarounds:
1) In the above thread, a workaround mentioned to change the code page before the install. Maybe you'll have better luck with this code page before installing mssql-cli.
```
> chcp 866
```

2) Upgrade to pip 10. This is a beta version, but should be fine to use. After upgrading pip with the below command, you can try installing mssql-cli again.
```
python -m pip install --upgrade --pre pip
```  
Also, we're working on creating an MSI installer for mssql-cli. This should resolve issues like this. Hopefully we'll have something to share in the coming months.
