### ISSUE TITLE
SQL Server 2017 : Crash processing ON in INNER JOIN (ColumnMetadata object has no attribute 'get_foreign_keys')

### ISSUE THREAD

**Issue by jefflomax** [dbcli/mssql-cli#198]
Windows 10 1703 15063.0
SQL Server 2017
Version: 0.12.0
Connected as -I  (Integrated) to local DB

Query:
select * from Employees INNER JOIN "dbo"."Employees_Identities" ON 
Tried to display intellisense and returned:

XXXXX> select * from Employees INNER JOIN "dbo"."Employees_Identities" ON Exception in thread Thread-125:
Traceback (most recent call last):                                                                                     
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner                                            
    self.run()
  File "C:\Python\Python36\lib\threading.py", line 864, in runde                                                       
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Python36\lib\site-packages\prompt_toolkit\interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Python\Python36\lib\site-packages\mssqlcli\mssqlcompleter.py", line 446, in get_completions
    matches.extend(matcher(self, suggestion, word_before_cursor))
  File "C:\Python\Python36\lib\site-packages\mssqlcli\mssqlcompleter.py", line 618, in get_join_condition_matches
    for fk, lcol in fks:
  File "C:\Python\Python36\lib\site-packages\mssqlcli\mssqlcompleter.py", line 617, in <genexpr>
    fks = ((fk, lcol.name) for lcol in lcols for fk in lcol.get_foreign_keys)
**AttributeError: 'ColumnMetadata' object has no attribute 'get_foreign_keys'**

**Comment by MrMeemus** [comment]
A temporary workaround is to install our 0.10.0 release.

**Comment by MrMeemus** [comment]
@jefflomax, we just published a new release with the fix, feel free to upgrade.
