### ISSUE TITLE
Upgrade to prompt_toolkit 2.0

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/mssql-cli#226]
prompt_toolkit 2.0 is now pulled in by pgcli and IPython which in turn results in mssql-cli failing to start.

See https://github.com/dbcli/pgcli/pull/826

**Comment by MrMeemus** [comment]
@thorstenkampe , I don't quite follow. How is mssql-cli failing to start? I don't see the correlation as we don't pull in pgcli nor IPython...  Can you share a screenshot of your issue?

**Comment by thorstenkampe** [comment]
@MrMeemus  prompt_toolkit 2.0 is incompatible with 1.x. All dbcli applications are affected, pgcli und mycli have already upgraded or are in progress of doing so (see https://github.com/dbcli/mycli/pull/614).

Of course mssql-cli does not depend on pgcli or IPython. I mentioned these just as examples of popular applications which  - when upgrading - will pull in prompt_toolkit 2.0 and thus will make mssql-cli fail. (`pip` does not check other modules dependencies when upgrading a certain package).

**Comment by tsroten** [comment]
@thorstenkampe Installing mssql-cli via [pipsi](https://github.com/mitsuhiko/pipsi) could be a workaround for this.

**Comment by EvanCarroll** [comment]
Without hacking around it, this is the error you should receive.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ecarroll/code/mssql-cli/mssqlcli/main.py", line 101, in <module>
    main()
  File "/home/ecarroll/code/mssql-cli/mssqlcli/main.py", line 94, in main
    run_cli_with(mssqlcli_options)
  File "/home/ecarroll/code/mssql-cli/mssqlcli/main.py", line 50, in run_cli_with
    from mssqlcli.mssql_cli import MssqlCli
  File "/home/ecarroll/code/mssql-cli/mssqlcli/mssql_cli.py", line 27, in <module>
    from mssqlcli.completion_refresher import CompletionRefresher
  File "/home/ecarroll/code/mssql-cli/mssqlcli/completion_refresher.py", line 6, in <module>
    from .mssqlcompleter import MssqlCompleter
  File "/home/ecarroll/code/mssql-cli/mssqlcli/mssqlcompleter.py", line 8, in <module>
    from prompt_toolkit.contrib.completers import PathCompleter
ImportError: cannot import name 'PathCompleter'
```

**Comment by EvanCarroll** [comment]
If anyone wants to take this backport up from pgcli, 

* https://github.com/dbcli/pgcli/commit/392491a74d2d8abcb2c0db5230fc7f11502c6ba9

**Comment by MrMeemus** [comment]
I have all the code changes in on my new branch. Will have to test a few scenarios before sending out PR. Thanks all!

**Comment by techvslife** [comment]
I'm adding details on the installation issue with mssql-cli caused by the dependence on an old version of prompt-toolkit:
Installing this on win10 x64 using pip auto-downgrades (without choice) prompt-toolkit to 1.x, which is a conflict with jupyter and ipython:
```
jupyter-console 6.0.0 has requirement prompt_toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.16 which is incompatible.
ipython 7.2.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.16 which is incompatible.

```
I had to manually upgrade it back:
`pip install --upgrade prompt-toolkit`

But that means a conflict with mssql-cli:
`mssql-cli 0.15.0 has requirement prompt-toolkit<1.1.0,>=1.0.10, but you'll have prompt-toolkit 2.0.9 which is incompatible.`

**Comment by techvslife** [comment]
Here is the text of the error that results when trying to use mssql-cli with the newer (2.x) version of prompt-toolkit (when trying to login in to an sql server database):

```
Traceback (most recent call last):
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\mssqlcli\main.py", line 94, in <module>
    run_cli_with(mssqlcli_options)
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\mssqlcli\main.py", line 50, in run_cli_with
    from mssqlcli.mssql_cli import MssqlCli
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\mssqlcli\mssql_cli.py", line 27, in <module>
    from mssqlcli.completion_refresher import CompletionRefresher
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\mssqlcli\completion_refresher.py", line 6, in <module>
    from .mssqlcompleter import MssqlCompleter
  File "C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\mssqlcli\mssqlcompleter.py", line 8, in <module>
    from prompt_toolkit.contrib.completers import PathCompleter
ImportError: cannot import name 'PathCompleter' from 'prompt_toolkit.contrib.completers' (C:\Users\usr_name\AppData\Local\Continuum\anaconda3\lib\site-packages\prompt_toolkit\contrib\completers\__init__.py)
```

**Comment by noraj** [comment]
```
mssql-cli -U sa -P password -d dbname -S x.x.x.x
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/mssqlcli/main.py", line 94, in <module>
    run_cli_with(mssqlcli_options)
  File "/usr/lib/python3.7/site-packages/mssqlcli/main.py", line 50, in run_cli_with
    from mssqlcli.mssql_cli import MssqlCli
  File "/usr/lib/python3.7/site-packages/mssqlcli/mssql_cli.py", line 27, in <module>
    from mssqlcli.completion_refresher import CompletionRefresher
  File "/usr/lib/python3.7/site-packages/mssqlcli/completion_refresher.py", line 6, in <module>
    from .mssqlcompleter import MssqlCompleter
  File "/usr/lib/python3.7/site-packages/mssqlcli/mssqlcompleter.py", line 8, in <module>
    from prompt_toolkit.contrib.completers import PathCompleter
ImportError: cannot import name 'PathCompleter' from 'prompt_toolkit.contrib.completers' (/usr/lib/python3.7/site-packages/prompt_toolkit/contrib/completers/__init__.py)
```

With 2.0.9

**Comment by noraj** [comment]
Workaround with a python3 virtual env:

```
$ python -m venv venv
$ source venv/bin/activate
$ which pip
/current/path/here/venv/bin/pip
$ pip install mssql-cli
$ mssql-cli -U sa -P password -d dbname -S x.x.x.x
```

**Comment by pensivebrian** [comment]
The upgraded to prompt_toolkit 2.0 has been completed in the 0.16.0 release available on pypi. We'll be pushing out .deb and .rpm packages soon.
