### ISSUE TITLE
ImportError: cannot import name 'PathCompleter'.......

### ISSUE THREAD

**Issue by notaduck** [dbcli/mssql-cli#244]
I've installe mssql-cli through the AUR repository however I get the error you can see in the paste if I try to connect to a server?

```
$ mssql-cli -S dbo-server.database.windows.net                                                  
Username (press enter for sa):xxxx
Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/mssqlcli/main.py", line 94, in <module>
    run_cli_with(mssqlcli_options)
  File "/usr/lib/python3.7/site-packages/mssqlcli/main.py", line 50, in run_cli_with
    from mssqlcli.mssql_cli import MssqlCli
  File "/usr/lib/python3.7/site-packages/mssqlcli/mssql_cli.py", line 27, in <module>
    from mssqlcli.completion_refresher import CompletionRefresher
  File "/usr/lib/python3.7/site-packages/mssqlcli/completion_refresher.py", line 6, in <module>
    from .mssqlcompleter import MssqlCompleter
  File "/usr/lib/python3.7/site-packages/mssqlcli/mssqlcompleter.py", line 8, in <module>
    from prompt_toolkit.contrib.completers import PathCompleter
ImportError: cannot import name 'PathCompleter' from 'prompt_toolkit.contrib.completers' (/usr/lib/python3.7/site-packages/prompt_toolkit/contrib/completers/__init__.py)

```

**Comment by MrMeemus** [comment]
@notaduck , Do you have prompt tool kit 2.0 installed? perhaps from a mycli or pgcli install? This issue is basically a clash in the dependency of prompt tool kit between mssql-cli and pgcli etc. I have a PR out for updating our dependency that should fix this issue. For now I would recommend installing mssql-cli in it's own virtual environment to avoid cross dependency conflicts.

**Comment by notaduck** [comment]
Yup, I've mycli installed. I guess that is the issue then.
Thanks for the quick reply!
