### ISSUE TITLE
Add support for SUSE Linux Enterprise Server 12

### ISSUE THREAD

**Issue by ellbosch** [dbcli/mssql-cli#470]
SLES 12 is supported on both SQL Server and .NET core. It is recommended that mssql-cli adds support for this platform as well.

0.15.0 is the last supported release for SLES 12.

**Comment by jamesongithub** [comment]
Not sure what this means:

`0.15.0 is the last supported release for SLES 12.`

But it doesn't look like it's working (seems to be available on the sles 12 msft repos)

```bash
mssql-cli 
Username (press enter for sa):
Password: 
Traceback (most recent call last):
  File "/usr/lib64/mssql-cli/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/mssql-cli/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/mssqlcli/main.py", line 101, in <module>
    run_cli_with(mssqlcli_options)
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/mssqlcli/main.py", line 51, in run_cli_with
    from mssqlcli.mssql_cli import MssqlCli
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/mssqlcli/mssql_cli.py", line 12, in <module>
    from cli_helpers.tabular_output import TabularOutputFormatter
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    from .output_formatter import format_output, TabularOutputFormatter
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/cli_helpers/tabular_output/output_formatter.py", line 10, in <module>
    from . import (delimited_output_adapter, vertical_table_adapter,
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/cli_helpers/tabular_output/terminaltables_adapter.py", line 4, in <module>
    import terminaltables
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/__init__.py", line 9, in <module>
    from terminaltables.ascii_table import AsciiTable  # noqa
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/ascii_table.py", line 3, in <module>
    from terminaltables.base_table import BaseTable
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/base_table.py", line 3, in <module>
    from terminaltables.build import build_border, build_row, flatten
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/build.py", line 3, in <module>
    from terminaltables.width_and_alignment import visible_width
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/width_and_alignment.py", line 6, in <module>
    from terminaltables.terminal_io import terminal_size
  File "/usr/lib64/mssql-cli/lib/python3.6/site-packages/terminaltables/terminal_io.py", line 3, in <module>
    import ctypes
  File "/usr/lib64/mssql-cli/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```


`Retrieving package mssql-cli-0.15.0-1.el7.x86_64 `

Looks like this is the rhel package uploaded to the sles repos.

Could we get one for sles12 and sles15?
